// resources/js/components/displays/currency.vue
<template>
    <span>Rp. {{displayValue}}</span>
</template>

<script>
export default {
    name: "currency",
    props: ["value"],
    computed: {
        displayValue:function () {
            return helper.currency.displayCurrency(this.$props.value)
        }
    }
}
</script>

<style scoped>

</style>

// resources/js/react/components/display/currency.jsx
import React, {Component} from 'react';
import {displayCurrency} from "@/helper/formatter";

class Currency extends Component {
    render() {
        return (
            <span>
                Rp. {displayCurrency(this.props.value ?? 0)}
            </span>
        );
    }
}

export default Currency;
