// resources/js/react/components/Button.jsx
import React, {Component} from 'react';
import {getSizeClass, SIZE_SMALL} from "@/helper/size";
import {COLOR_PRIMARY, getColorClass} from "@/helper/color";

const prefixClass = 'btn-'

class Button extends Component {

    render() {
        return (
            <button className={[
                "btn",
                this.props.fullWidth ? "btn-block" : null,
                this.props.rounded ? "btn-rounded" : null,
                this.props.circle ? "btn-circle" : null,
                this.props.size ? getSizeClass(prefixClass, this.props.size) : null,
                this.props.color ? getColorClass(prefixClass, this.props.color,this.props.outline) : null
            ].join(" ")}>{this.props.children}</button>

        );
    }
}

Button.defaultProps = {
    fullWidth: false,
    rounded: false,
    circle: false,
    outline: false,
    size: SIZE_SMALL,
    color: COLOR_PRIMARY,

}
export default Button;

// resources/js/components/ButtonComponent.vue
<template>
    <button
        class="btn"
        :class="[{
        'btn-rounded' : rounded,
        'btn-circle' : circle,
        },
        size?`btn-${size}`:undefined,
        color?$consts.color.getColorClass('btn-',color,outline):undefined
        ]"
    >
        <slot/>
    </button>

</template>

<script>
export default {
    name:"ButtonComponent",
    props: {
        rounded: Boolean,
        circle: Boolean,
        outline: Boolean,
        color: {
            type: String,
            default: consts.color.COLOR_PRIMARY,
        },
        size: {
            type: String,
        },
    }

}
</script>

<style scoped>

</style>
